
trigger:
- main

pool: Azure Pipelines

variables:
  buildConfiguration: 'Release'

steps:
- bash: echo hello world

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'
 